matchups:
- report: data/reports/comparisons/2023_w17/CLE_vs_NYJ.md
  home: CLE
  away: NYJ
  spread: -5.5
  total: 34.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w17/DAL_vs_DET.md
  home: DAL
  away: DET
  spread: -6.0
  total: 53.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w17/NYG_vs_LA.md
  home: NYG
  away: LA
  spread: 6.0
  total: 41.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w17/PHI_vs_ARI.md
  home: PHI
  away: ARI
  spread: -10.0
  total: 47.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w17/TB_vs_NO.md
  home: TB
  away: 'NO'
  spread: -2.0
  total: 41.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w17/WAS_vs_SF.md
  home: WAS
  away: SF
  spread: 13.5
  total: 48.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w17/HOU_vs_TEN.md
  home: HOU
  away: TEN
  spread: -4.5
  total: 43.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w17/BUF_vs_NE.md
  home: BUF
  away: NE
  spread: -12.5
  total: 40.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w17/CHI_vs_ATL.md
  home: CHI
  away: ATL
  spread: -3.0
  total: 37.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w17/IND_vs_LV.md
  home: IND
  away: LV
  spread: -3.0
  total: 44.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w17/JAX_vs_CAR.md
  home: JAX
  away: CAR
  spread: -9.0
  total: 38.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w17/BAL_vs_MIA.md
  home: BAL
  away: MIA
  spread: -3.0
  total: 47.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w17/SEA_vs_PIT.md
  home: SEA
  away: PIT
  spread: -3.5
  total: 40.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w17/DEN_vs_LAC.md
  home: DEN
  away: LAC
  spread: -6.0
  total: 38.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w17/KC_vs_CIN.md
  home: KC
  away: CIN
  spread: -7.5
  total: 44.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w17/MIN_vs_GB.md
  home: MIN
  away: GB
  spread: -2.0
  total: 43.5
  prime_time: true
  neutral_site: false
