matchups:
- report: data/reports/comparisons/2023_w12/DET_vs_GB.md
  home: DET
  away: GB
  spread: -7.5
  total: 45.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w12/DAL_vs_WAS.md
  home: DAL
  away: WAS
  spread: -11.0
  total: 48.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w12/SEA_vs_SF.md
  home: SEA
  away: SF
  spread: 6.5
  total: 43.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w12/NYJ_vs_MIA.md
  home: NYJ
  away: MIA
  spread: 7.5
  total: 42.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w12/ATL_vs_NO.md
  home: ATL
  away: 'NO'
  spread: -0.5
  total: 41.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w12/TEN_vs_CAR.md
  home: TEN
  away: CAR
  spread: -4.0
  total: 37.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w12/NYG_vs_NE.md
  home: NYG
  away: NE
  spread: 3.5
  total: 34.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w12/CIN_vs_PIT.md
  home: CIN
  away: PIT
  spread: 1.0
  total: 35.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w12/IND_vs_TB.md
  home: IND
  away: TB
  spread: -1.5
  total: 42.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w12/HOU_vs_JAX.md
  home: HOU
  away: JAX
  spread: 1.0
  total: 46.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w12/DEN_vs_CLE.md
  home: DEN
  away: CLE
  spread: -2.0
  total: 36.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w12/ARI_vs_LA.md
  home: ARI
  away: LA
  spread: 1.0
  total: 46.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w12/LV_vs_KC.md
  home: LV
  away: KC
  spread: 9.5
  total: 44.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w12/PHI_vs_BUF.md
  home: PHI
  away: BUF
  spread: -3.0
  total: 47.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w12/LAC_vs_BAL.md
  home: LAC
  away: BAL
  spread: 4.0
  total: 46.0
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w12/MIN_vs_CHI.md
  home: MIN
  away: CHI
  spread: -3.5
  total: 45.5
  prime_time: true
  neutral_site: false
