matchups:
- report: data/reports/comparisons/2023_w14/PIT_vs_NE.md
  home: PIT
  away: NE
  spread: -6.0
  total: 30.0
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w14/CHI_vs_DET.md
  home: CHI
  away: DET
  spread: 3.0
  total: 40.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w14/NO_vs_CAR.md
  home: 'NO'
  away: CAR
  spread: -5.0
  total: 37.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w14/BAL_vs_LA.md
  home: BAL
  away: LA
  spread: -7.0
  total: 40.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w14/ATL_vs_TB.md
  home: ATL
  away: TB
  spread: -2.5
  total: 39.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w14/CIN_vs_IND.md
  home: CIN
  away: IND
  spread: 1.0
  total: 40.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w14/CLE_vs_JAX.md
  home: CLE
  away: JAX
  spread: -3.0
  total: 30.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w14/NYJ_vs_HOU.md
  home: NYJ
  away: HOU
  spread: 5.5
  total: 33.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w14/LV_vs_MIN.md
  home: LV
  away: MIN
  spread: 3.0
  total: 40.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w14/SF_vs_SEA.md
  home: SF
  away: SEA
  spread: -10.5
  total: 46.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w14/KC_vs_BUF.md
  home: KC
  away: BUF
  spread: -2.5
  total: 47.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w14/LAC_vs_DEN.md
  home: LAC
  away: DEN
  spread: -3.0
  total: 44.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w14/DAL_vs_PHI.md
  home: DAL
  away: PHI
  spread: -3.5
  total: 53.0
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w14/MIA_vs_TEN.md
  home: MIA
  away: TEN
  spread: -13.5
  total: 47.0
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w14/NYG_vs_GB.md
  home: NYG
  away: GB
  spread: 6.5
  total: 37.0
  prime_time: true
  neutral_site: false
