matchups:
- report: data/reports/comparisons/2023_w6/LAC_vs_DAL.md
  home: LAC
  away: DAL
  spread: 1.5
  total: 50.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w6/BUF_vs_NYG.md
  home: BUF
  away: NYG
  spread: -15.5
  total: 43.0
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w6/LV_vs_NE.md
  home: LV
  away: NE
  spread: -3.0
  total: 41.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w6/TEN_vs_BAL.md
  home: TEN
  away: BAL
  spread: 5.5
  total: 42.5
  prime_time: false
  neutral_site: true
- report: data/reports/comparisons/2023_w6/JAX_vs_IND.md
  home: JAX
  away: IND
  spread: -3.5
  total: 44.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w6/CLE_vs_SF.md
  home: CLE
  away: SF
  spread: 9.5
  total: 36.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w6/LA_vs_ARI.md
  home: LA
  away: ARI
  spread: -7.0
  total: 47.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w6/NYJ_vs_PHI.md
  home: NYJ
  away: PHI
  spread: 6.5
  total: 43.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w6/TB_vs_DET.md
  home: TB
  away: DET
  spread: 3.0
  total: 42.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w6/HOU_vs_NO.md
  home: HOU
  away: 'NO'
  spread: 1.5
  total: 42.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w6/ATL_vs_WAS.md
  home: ATL
  away: WAS
  spread: -1.5
  total: 42.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w6/CIN_vs_SEA.md
  home: CIN
  away: SEA
  spread: -3.0
  total: 45.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w6/MIA_vs_CAR.md
  home: MIA
  away: CAR
  spread: -14.5
  total: 47.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w6/CHI_vs_MIN.md
  home: CHI
  away: MIN
  spread: 3.0
  total: 43.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w6/KC_vs_DEN.md
  home: KC
  away: DEN
  spread: -10.5
  total: 47.5
  prime_time: true
  neutral_site: false
