matchups:
- report: data/reports/comparisons/2023_w2/PHI_vs_MIN.md
  home: PHI
  away: MIN
  spread: -6.5
  total: 48.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w2/ATL_vs_GB.md
  home: ATL
  away: GB
  spread: -3.0
  total: 40.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w2/CIN_vs_BAL.md
  home: CIN
  away: BAL
  spread: -3.5
  total: 45.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w2/TEN_vs_LAC.md
  home: TEN
  away: LAC
  spread: 2.5
  total: 45.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w2/BUF_vs_LV.md
  home: BUF
  away: LV
  spread: -7.5
  total: 46.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w2/TB_vs_CHI.md
  home: TB
  away: CHI
  spread: -2.5
  total: 40.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w2/HOU_vs_IND.md
  home: HOU
  away: IND
  spread: -1.0
  total: 39.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w2/JAX_vs_KC.md
  home: JAX
  away: KC
  spread: 3.5
  total: 50.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w2/DET_vs_SEA.md
  home: DET
  away: SEA
  spread: -4.5
  total: 47.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w2/DEN_vs_WAS.md
  home: DEN
  away: WAS
  spread: -3.5
  total: 38.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w2/DAL_vs_NYJ.md
  home: DAL
  away: NYJ
  spread: -8.5
  total: 38.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w2/ARI_vs_NYG.md
  home: ARI
  away: NYG
  spread: 4.5
  total: 39.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w2/NE_vs_MIA.md
  home: NE
  away: MIA
  spread: 2.5
  total: 46.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w2/PIT_vs_CLE.md
  home: PIT
  away: CLE
  spread: 2.5
  total: 38.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w2/CAR_vs_NO.md
  home: CAR
  away: 'NO'
  spread: 3.0
  total: 39.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w2/LA_vs_SF.md
  home: LA
  away: SF
  spread: 7.5
  total: 45.5
  prime_time: false
  neutral_site: false
