matchups:
- report: data/reports/comparisons/2023_w1/KC_vs_DET.md
  home: KC
  away: DET
  spread: -6.5
  total: 54.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w1/ATL_vs_CAR.md
  home: ATL
  away: CAR
  spread: -3.5
  total: 40.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w1/BAL_vs_HOU.md
  home: BAL
  away: HOU
  spread: -9.5
  total: 43.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w1/CLE_vs_CIN.md
  home: CLE
  away: CIN
  spread: 1.5
  total: 46.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w1/IND_vs_JAX.md
  home: IND
  away: JAX
  spread: 3.5
  total: 45.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w1/MIN_vs_TB.md
  home: MIN
  away: TB
  spread: -4.5
  total: 44.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w1/NO_vs_TEN.md
  home: 'NO'
  away: TEN
  spread: -3.0
  total: 41.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w1/PIT_vs_SF.md
  home: PIT
  away: SF
  spread: 1.5
  total: 41.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w1/WAS_vs_ARI.md
  home: WAS
  away: ARI
  spread: -6.5
  total: 38.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w1/CHI_vs_GB.md
  home: CHI
  away: GB
  spread: -1.5
  total: 40.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w1/DEN_vs_LV.md
  home: DEN
  away: LV
  spread: -3.5
  total: 43.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w1/LAC_vs_MIA.md
  home: LAC
  away: MIA
  spread: -3.0
  total: 50.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w1/NE_vs_PHI.md
  home: NE
  away: PHI
  spread: 3.5
  total: 44.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w1/SEA_vs_LA.md
  home: SEA
  away: LA
  spread: -4.5
  total: 45.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w1/NYG_vs_DAL.md
  home: NYG
  away: DAL
  spread: 3.5
  total: 44.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w1/NYJ_vs_BUF.md
  home: NYJ
  away: BUF
  spread: 2.0
  total: 45.5
  prime_time: true
  neutral_site: false
