matchups:
- report: data/reports/comparisons/2023_w8/DET_vs_LV.md
  home: DET
  away: LV
  spread: -7.5
  total: 46.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w8/DEN_vs_KC.md
  home: DEN
  away: KC
  spread: 7.0
  total: 46.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w8/DAL_vs_LA.md
  home: DAL
  away: LA
  spread: -7.0
  total: 44.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w8/SF_vs_CIN.md
  home: SF
  away: CIN
  spread: -4.0
  total: 44.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w8/MIA_vs_NE.md
  home: MIA
  away: NE
  spread: -7.5
  total: 46.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w8/CAR_vs_HOU.md
  home: CAR
  away: HOU
  spread: 3.5
  total: 43.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w8/GB_vs_MIN.md
  home: GB
  away: MIN
  spread: 1.0
  total: 41.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w8/WAS_vs_PHI.md
  home: WAS
  away: PHI
  spread: 7.0
  total: 43.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w8/SEA_vs_CLE.md
  home: SEA
  away: CLE
  spread: -3.5
  total: 38.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w8/ARI_vs_BAL.md
  home: ARI
  away: BAL
  spread: 9.5
  total: 44.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w8/IND_vs_NO.md
  home: IND
  away: 'NO'
  spread: 2.0
  total: 43.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w8/LAC_vs_CHI.md
  home: LAC
  away: CHI
  spread: -9.5
  total: 46.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w8/TEN_vs_ATL.md
  home: TEN
  away: ATL
  spread: 2.5
  total: 35.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w8/NYJ_vs_NYG.md
  home: NYJ
  away: NYG
  spread: -3.0
  total: 35.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w8/PIT_vs_JAX.md
  home: PIT
  away: JAX
  spread: 2.5
  total: 41.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w8/BUF_vs_TB.md
  home: BUF
  away: TB
  spread: -10.0
  total: 43.0
  prime_time: true
  neutral_site: false
