matchups:
- report: data/reports/comparisons/2023_w3/TB_vs_PHI.md
  home: TB
  away: PHI
  spread: 5.5
  total: 44.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w3/CIN_vs_LA.md
  home: CIN
  away: LA
  spread: -3.0
  total: 45.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w3/ARI_vs_DAL.md
  home: ARI
  away: DAL
  spread: 12.5
  total: 43.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w3/LV_vs_PIT.md
  home: LV
  away: PIT
  spread: -3.0
  total: 43.0
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w3/SEA_vs_CAR.md
  home: SEA
  away: CAR
  spread: -5.0
  total: 42.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w3/KC_vs_CHI.md
  home: KC
  away: CHI
  spread: -12.5
  total: 48.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w3/JAX_vs_HOU.md
  home: JAX
  away: HOU
  spread: -7.5
  total: 43.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w3/CLE_vs_TEN.md
  home: CLE
  away: TEN
  spread: -3.5
  total: 38.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w3/MIA_vs_DEN.md
  home: MIA
  away: DEN
  spread: -6.0
  total: 47.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w3/NYJ_vs_NE.md
  home: NYJ
  away: NE
  spread: 2.5
  total: 35.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w3/WAS_vs_BUF.md
  home: WAS
  away: BUF
  spread: 5.5
  total: 44.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w3/BAL_vs_IND.md
  home: BAL
  away: IND
  spread: -7.5
  total: 43.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w3/DET_vs_ATL.md
  home: DET
  away: ATL
  spread: -3.0
  total: 47.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w3/GB_vs_NO.md
  home: GB
  away: 'NO'
  spread: 1.5
  total: 41.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w3/MIN_vs_LAC.md
  home: MIN
  away: LAC
  spread: -1.0
  total: 53.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w3/SF_vs_NYG.md
  home: SF
  away: NYG
  spread: -10.0
  total: 44.5
  prime_time: true
  neutral_site: false
