matchups:
- report: data/reports/comparisons/2023_w10/CHI_vs_CAR.md
  home: CHI
  away: CAR
  spread: -3.0
  total: 40.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w10/IND_vs_NE.md
  home: IND
  away: NE
  spread: -1.5
  total: 43.5
  prime_time: false
  neutral_site: true
- report: data/reports/comparisons/2023_w10/MIN_vs_NO.md
  home: MIN
  away: 'NO'
  spread: 2.5
  total: 40.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w10/JAX_vs_SF.md
  home: JAX
  away: SF
  spread: 2.5
  total: 44.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w10/BAL_vs_CLE.md
  home: BAL
  away: CLE
  spread: -5.5
  total: 39.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w10/CIN_vs_HOU.md
  home: CIN
  away: HOU
  spread: -8.0
  total: 46.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w10/PIT_vs_GB.md
  home: PIT
  away: GB
  spread: -3.0
  total: 37.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w10/TB_vs_TEN.md
  home: TB
  away: TEN
  spread: -1.0
  total: 39.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w10/ARI_vs_ATL.md
  home: ARI
  away: ATL
  spread: 2.5
  total: 41.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w10/LAC_vs_DET.md
  home: LAC
  away: DET
  spread: 1.5
  total: 48.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w10/DAL_vs_NYG.md
  home: DAL
  away: NYG
  spread: -15.5
  total: 39.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w10/SEA_vs_WAS.md
  home: SEA
  away: WAS
  spread: -6.0
  total: 44.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w10/LV_vs_NYJ.md
  home: LV
  away: NYJ
  spread: 2.0
  total: 36.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w10/BUF_vs_DEN.md
  home: BUF
  away: DEN
  spread: -7.5
  total: 45.5
  prime_time: true
  neutral_site: false
