matchups:
- report: data/reports/comparisons/2023_w15/PHI_vs_WAS.md
  home: PHI
  away: WAS
  spread: -10.0
  total: 39.0
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w15/LA_vs_WAS.md
  home: LA
  away: WAS
  spread: -7.0
  total: 47.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w15/CHI_vs_MIN.md
  home: CHI
  away: MIN
  spread: 7.0
  total: 47.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w15/CLE_vs_CHI.md
  home: CLE
  away: CHI
  spread: 3.0
  total: 40.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w15/TB_vs_FALSE.md
  home: TB
  away: 'FALSE'
  spread: -11.5
  total: 46.0
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w15/BAL_vs_GB.md
  home: BAL
  away: GB
  spread: 5.5
  total: 43.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w15/DET_vs_DEN.md
  home: DET
  away: DEN
  spread: 13.0
  total: 48.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w15/NYG_vs_DAL.md
  home: NYG
  away: DAL
  spread: 12.5
  total: 43.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w15/JAX_vs_BAL.md
  home: JAX
  away: BAL
  spread: -6.0
  total: 40.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w15/SF_vs_ATL.md
  home: SF
  away: ATL
  spread: -9.5
  total: 46.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w15/BUF_vs_DAL.md
  home: BUF
  away: DAL
  spread: -14.5
  total: 43.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w15/MIA_vs_NYJ.md
  home: MIA
  away: NYJ
  spread: -10.0
  total: 42.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w15/PIT_vs_TEN.md
  home: PIT
  away: TEN
  spread: -1.5
  total: 43.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w15/DEN_vs_CIN.md
  home: DEN
  away: CIN
  spread: -1.5
  total: 43.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w15/IND_vs_PIT.md
  home: IND
  away: PIT
  spread: -1.0
  total: 46.0
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w15/LAC_vs_KC.md
  home: LAC
  away: KC
  spread: 3.0
  total: 54.0
  prime_time: true
  neutral_site: false
