matchups:
- report: data/reports/comparisons/2023_w16/LA_vs_NO.md
  home: LA
  away: 'NO'
  spread: -4.0
  total: 44.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w16/PIT_vs_CIN.md
  home: PIT
  away: CIN
  spread: -1.0
  total: 39.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w16/LAC_vs_BUF.md
  home: LAC
  away: BUF
  spread: 12.0
  total: 44.0
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w16/ATL_vs_IND.md
  home: ATL
  away: IND
  spread: -2.5
  total: 45.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w16/MIN_vs_DET.md
  home: MIN
  away: DET
  spread: 3.0
  total: 47.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w16/CAR_vs_GB.md
  home: CAR
  away: GB
  spread: 4.0
  total: 37.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w16/TEN_vs_SEA.md
  home: TEN
  away: SEA
  spread: 3.5
  total: 41.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w16/NYJ_vs_WAS.md
  home: NYJ
  away: WAS
  spread: -3.0
  total: 37.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w16/HOU_vs_CLE.md
  home: HOU
  away: CLE
  spread: 3.0
  total: 40.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w16/TB_vs_JAX.md
  home: TB
  away: JAX
  spread: 1.0
  total: 43.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w16/CHI_vs_ARI.md
  home: CHI
  away: ARI
  spread: -4.0
  total: 43.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w16/MIA_vs_DAL.md
  home: MIA
  away: DAL
  spread: -1.5
  total: 49.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w16/DEN_vs_NE.md
  home: DEN
  away: NE
  spread: -7.0
  total: 35.0
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w16/KC_vs_LV.md
  home: KC
  away: LV
  spread: -10.5
  total: 40.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w16/PHI_vs_NYG.md
  home: PHI
  away: NYG
  spread: -13.5
  total: 43.0
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w16/SF_vs_BAL.md
  home: SF
  away: BAL
  spread: -6.0
  total: 47.0
  prime_time: true
  neutral_site: false
