matchups:
- report: data/reports/comparisons/2023_w5/LV_vs_GB.md
  home: LV
  away: GB
  spread: -1.5
  total: 44.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w5/SF_vs_DAL.md
  home: SF
  away: DAL
  spread: -3.5
  total: 45.0
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w5/LA_vs_PHI.md
  home: LA
  away: PHI
  spread: 4.0
  total: 50.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w5/MIN_vs_KC.md
  home: MIN
  away: KC
  spread: 3.5
  total: 52.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w5/ARI_vs_CIN.md
  home: ARI
  away: CIN
  spread: 3.0
  total: 44.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w5/DEN_vs_NYJ.md
  home: DEN
  away: NYJ
  spread: -2.5
  total: 42.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w5/DET_vs_CAR.md
  home: DET
  away: CAR
  spread: -9.5
  total: 43.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w5/MIA_vs_NYG.md
  home: MIA
  away: NYG
  spread: -12.5
  total: 47.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w5/IND_vs_TEN.md
  home: IND
  away: TEN
  spread: 2.5
  total: 42.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w5/NE_vs_NO.md
  home: NE
  away: 'NO'
  spread: -1.5
  total: 39.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w5/PIT_vs_BAL.md
  home: PIT
  away: BAL
  spread: 4.5
  total: 38.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w5/BUF_vs_JAX.md
  home: BUF
  away: JAX
  spread: -5.5
  total: 48.5
  prime_time: false
  neutral_site: true
- report: data/reports/comparisons/2023_w5/ATL_vs_HOU.md
  home: ATL
  away: HOU
  spread: -2.5
  total: 42.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w5/WAS_vs_CHI.md
  home: WAS
  away: CHI
  spread: -6.0
  total: 45.5
  prime_time: true
  neutral_site: false
