matchups:
- report: data/reports/comparisons/2023_w7/MIN_vs_SF.md
  home: MIN
  away: SF
  spread: 7.0
  total: 43.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w7/PHI_vs_MIA.md
  home: PHI
  away: MIA
  spread: -3.0
  total: 51.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2023_w7/KC_vs_LAC.md
  home: KC
  away: LAC
  spread: -5.5
  total: 47.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w7/DEN_vs_GB.md
  home: DEN
  away: GB
  spread: -1.5
  total: 45.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w7/LA_vs_PIT.md
  home: LA
  away: PIT
  spread: -3.0
  total: 44.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w7/SEA_vs_ARI.md
  home: SEA
  away: ARI
  spread: -8.0
  total: 44.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w7/CHI_vs_LV.md
  home: CHI
  away: LV
  spread: 2.5
  total: 37.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w7/TB_vs_ATL.md
  home: TB
  away: ATL
  spread: -2.5
  total: 37.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w7/BAL_vs_DET.md
  home: BAL
  away: DET
  spread: -3.0
  total: 43.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w7/IND_vs_CLE.md
  home: IND
  away: CLE
  spread: 3.5
  total: 41.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w7/NE_vs_BUF.md
  home: NE
  away: BUF
  spread: 7.5
  total: 40.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w7/NYG_vs_WAS.md
  home: NYG
  away: WAS
  spread: 3.0
  total: 37.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2023_w7/NO_vs_JAX.md
  home: 'NO'
  away: JAX
  spread: -2.5
  total: 41.5
  prime_time: true
  neutral_site: false
