matchups:
- report: data/reports/comparisons/2022_w12/DET_vs_BUF.md
  home: DET
  away: BUF
  spread: 10.0
  total: 54.0
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w12/DAL_vs_NYG.md
  home: DAL
  away: NYG
  spread: -10.5
  total: 45.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w12/MIN_vs_NE.md
  home: MIN
  away: NE
  spread: -2.5
  total: 42.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w12/TEN_vs_CIN.md
  home: TEN
  away: CIN
  spread: 1.0
  total: 43.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w12/CLE_vs_TB.md
  home: CLE
  away: TB
  spread: 3.0
  total: 42.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w12/MIA_vs_HOU.md
  home: MIA
  away: HOU
  spread: -14.0
  total: 47.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w12/JAX_vs_BAL.md
  home: JAX
  away: BAL
  spread: 3.5
  total: 43.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w12/WAS_vs_ATL.md
  home: WAS
  away: ATL
  spread: -3.5
  total: 40.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w12/CAR_vs_DEN.md
  home: CAR
  away: DEN
  spread: 1.0
  total: 36.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w12/NYJ_vs_CHI.md
  home: NYJ
  away: CHI
  spread: -8.5
  total: 36.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w12/SEA_vs_LV.md
  home: SEA
  away: LV
  spread: -4.0
  total: 47.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w12/ARI_vs_LAC.md
  home: ARI
  away: LAC
  spread: 2.5
  total: 48.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w12/KC_vs_LA.md
  home: KC
  away: LA
  spread: -16.5
  total: 42.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w12/SF_vs_NO.md
  home: SF
  away: 'NO'
  spread: -9.5
  total: 44.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w12/PHI_vs_GB.md
  home: PHI
  away: GB
  spread: -6.5
  total: 46.0
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w12/IND_vs_PIT.md
  home: IND
  away: PIT
  spread: -2.5
  total: 40.0
  prime_time: true
  neutral_site: false
