matchups:
- report: data/reports/comparisons/2022_w7/ARI_vs_NO.md
  home: ARI
  away: 'NO'
  spread: -2.5
  total: 44.0
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w7/CIN_vs_ATL.md
  home: CIN
  away: ATL
  spread: -6.5
  total: 47.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w7/CAR_vs_TB.md
  home: CAR
  away: TB
  spread: 13.0
  total: 39.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w7/BAL_vs_CLE.md
  home: BAL
  away: CLE
  spread: -6.5
  total: 46.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w7/TEN_vs_IND.md
  home: TEN
  away: IND
  spread: -2.5
  total: 43.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w7/DAL_vs_DET.md
  home: DAL
  away: DET
  spread: -7.0
  total: 49.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w7/WAS_vs_GB.md
  home: WAS
  away: GB
  spread: 4.0
  total: 41.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w7/JAX_vs_NYG.md
  home: JAX
  away: NYG
  spread: -3.0
  total: 44.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w7/LV_vs_HOU.md
  home: LV
  away: HOU
  spread: -7.0
  total: 46.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w7/NYJ_vs_DEN.md
  home: NYJ
  away: DEN
  spread: -2.0
  total: 37.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w7/SF_vs_KC.md
  home: SF
  away: KC
  spread: 1.0
  total: 49.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w7/LAC_vs_SEA.md
  home: LAC
  away: SEA
  spread: -5.5
  total: 51.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w7/MIA_vs_PIT.md
  home: MIA
  away: PIT
  spread: -7.5
  total: 44.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w7/NE_vs_CHI.md
  home: NE
  away: CHI
  spread: -9.5
  total: 40.0
  prime_time: true
  neutral_site: false
