matchups:
- report: data/reports/comparisons/2022_w17/TEN_vs_DAL.md
  home: TEN
  away: DAL
  spread: 14.0
  total: 41.0
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w17/ATL_vs_ARI.md
  home: ATL
  away: ARI
  spread: -7.0
  total: 41.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w17/TB_vs_CAR.md
  home: TB
  away: CAR
  spread: -3.5
  total: 40.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w17/DET_vs_CHI.md
  home: DET
  away: CHI
  spread: -4.5
  total: 52.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w17/WAS_vs_CLE.md
  home: WAS
  away: CLE
  spread: -1.0
  total: 41.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w17/NYG_vs_IND.md
  home: NYG
  away: IND
  spread: -5.5
  total: 38.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w17/KC_vs_DEN.md
  home: KC
  away: DEN
  spread: -13.5
  total: 46.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w17/HOU_vs_JAX.md
  home: HOU
  away: JAX
  spread: 3.5
  total: 43.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w17/NE_vs_MIA.md
  home: NE
  away: MIA
  spread: -3.0
  total: 41.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w17/PHI_vs_NO.md
  home: PHI
  away: 'NO'
  spread: -5.5
  total: 41.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w17/SEA_vs_NYJ.md
  home: SEA
  away: NYJ
  spread: 1.0
  total: 43.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w17/LV_vs_SF.md
  home: LV
  away: SF
  spread: 10.0
  total: 41.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w17/GB_vs_MIN.md
  home: GB
  away: MIN
  spread: -3.0
  total: 47.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w17/LAC_vs_LA.md
  home: LAC
  away: LA
  spread: -6.5
  total: 41.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w17/BAL_vs_PIT.md
  home: BAL
  away: PIT
  spread: -1.0
  total: 35.5
  prime_time: true
  neutral_site: false
