matchups:
- report: data/reports/comparisons/2022_w4/CIN_vs_MIA.md
  home: CIN
  away: MIA
  spread: -4.0
  total: 48.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w4/NO_vs_MIN.md
  home: 'NO'
  away: MIN
  spread: 4.0
  total: 42.0
  prime_time: false
  neutral_site: true
- report: data/reports/comparisons/2022_w4/ATL_vs_CLE.md
  home: ATL
  away: CLE
  spread: 1.0
  total: 48.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w4/BAL_vs_BUF.md
  home: BAL
  away: BUF
  spread: 3.0
  total: 50.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w4/NYG_vs_CHI.md
  home: NYG
  away: CHI
  spread: -3.0
  total: 39.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w4/IND_vs_TEN.md
  home: IND
  away: TEN
  spread: -4.5
  total: 43.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w4/DAL_vs_WAS.md
  home: DAL
  away: WAS
  spread: -3.0
  total: 40.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w4/DET_vs_SEA.md
  home: DET
  away: SEA
  spread: -3.0
  total: 48.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w4/HOU_vs_LAC.md
  home: HOU
  away: LAC
  spread: 5.5
  total: 45.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w4/PHI_vs_JAX.md
  home: PHI
  away: JAX
  spread: -6.5
  total: 44.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w4/PIT_vs_NYJ.md
  home: PIT
  away: NYJ
  spread: -3.0
  total: 41.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w4/CAR_vs_ARI.md
  home: CAR
  away: ARI
  spread: -1.0
  total: 44.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w4/LV_vs_DEN.md
  home: LV
  away: DEN
  spread: -2.5
  total: 45.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w4/GB_vs_NE.md
  home: GB
  away: NE
  spread: -10.0
  total: 40.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w4/TB_vs_KC.md
  home: TB
  away: KC
  spread: -1.0
  total: 46.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w4/SF_vs_LA.md
  home: SF
  away: LA
  spread: -1.0
  total: 42.0
  prime_time: true
  neutral_site: false
