matchups:
- report: data/reports/comparisons/2022_w9/HOU_vs_PHI.md
  home: HOU
  away: PHI
  spread: -14.0
  total: 45.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w9/NYJ_vs_BUF.md
  home: NYJ
  away: BUF
  spread: 11.0
  total: 46.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w9/DET_vs_GB.md
  home: DET
  away: GB
  spread: 4.0
  total: 49.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w9/WAS_vs_MIN.md
  home: WAS
  away: MIN
  spread: 3.0
  total: 43.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w9/ATL_vs_LAC.md
  home: ATL
  away: LAC
  spread: 2.5
  total: 49.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w9/CIN_vs_CAR.md
  home: CIN
  away: CAR
  spread: -7.0
  total: 43.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w9/CHI_vs_MIA.md
  home: CHI
  away: MIA
  spread: 4.0
  total: 46.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w9/NE_vs_IND.md
  home: NE
  away: IND
  spread: -5.0
  total: 40.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w9/JAX_vs_LV.md
  home: JAX
  away: LV
  spread: 2.5
  total: 47.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w9/ARI_vs_SEA.md
  home: ARI
  away: SEA
  spread: -1.5
  total: 49.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w9/TB_vs_LA.md
  home: TB
  away: LA
  spread: -3.0
  total: 43.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w9/KC_vs_TEN.md
  home: KC
  away: TEN
  spread: -14.0
  total: 45.0
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w9/NO_vs_BAL.md
  home: 'NO'
  away: BAL
  spread: 1.0
  total: 46.0
  prime_time: true
  neutral_site: false
