matchups:
- report: data/reports/comparisons/2022_w3/CLE_vs_PIT.md
  home: CLE
  away: PIT
  spread: -4.5
  total: 38.0
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w3/MIA_vs_BUF.md
  home: MIA
  away: BUF
  spread: 4.0
  total: 54.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w3/CAR_vs_NO.md
  home: CAR
  away: 'NO'
  spread: 2.0
  total: 41.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w3/CHI_vs_HOU.md
  home: CHI
  away: HOU
  spread: -3.0
  total: 40.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w3/NYJ_vs_CIN.md
  home: NYJ
  away: CIN
  spread: 6.5
  total: 46.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w3/IND_vs_KC.md
  home: IND
  away: KC
  spread: 4.5
  total: 51.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w3/MIN_vs_DET.md
  home: MIN
  away: DET
  spread: -6.5
  total: 52.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w3/NE_vs_BAL.md
  home: NE
  away: BAL
  spread: 2.5
  total: 45.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w3/TEN_vs_LV.md
  home: TEN
  away: LV
  spread: 1.5
  total: 45.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w3/WAS_vs_PHI.md
  home: WAS
  away: PHI
  spread: 6.0
  total: 47.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w3/LAC_vs_JAX.md
  home: LAC
  away: JAX
  spread: -6.5
  total: 46.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w3/SEA_vs_ATL.md
  home: SEA
  away: ATL
  spread: -1.0
  total: 43.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w3/ARI_vs_LA.md
  home: ARI
  away: LA
  spread: 3.5
  total: 49.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w3/TB_vs_GB.md
  home: TB
  away: GB
  spread: -1.0
  total: 41.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w3/DEN_vs_SF.md
  home: DEN
  away: SF
  spread: 1.0
  total: 44.0
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w3/NYG_vs_DAL.md
  home: NYG
  away: DAL
  spread: -1.0
  total: 38.5
  prime_time: true
  neutral_site: false
