matchups:
- report: data/reports/comparisons/2022_w18/LV_vs_KC.md
  home: LV
  away: KC
  spread: 9.0
  total: 51.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w18/JAX_vs_TEN.md
  home: JAX
  away: TEN
  spread: -6.0
  total: 39.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w18/BUF_vs_NE.md
  home: BUF
  away: NE
  spread: -8.0
  total: 44.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w18/CIN_vs_BAL.md
  home: CIN
  away: BAL
  spread: -11.0
  total: 39.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w18/ATL_vs_TB.md
  home: ATL
  away: TB
  spread: -6.0
  total: 40.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w18/NO_vs_CAR.md
  home: 'NO'
  away: CAR
  spread: -3.5
  total: 41.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w18/CHI_vs_MIN.md
  home: CHI
  away: MIN
  spread: 6.5
  total: 42.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w18/PIT_vs_CLE.md
  home: PIT
  away: CLE
  spread: -2.5
  total: 40.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w18/IND_vs_HOU.md
  home: IND
  away: HOU
  spread: -3.0
  total: 38.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w18/MIA_vs_NYJ.md
  home: MIA
  away: NYJ
  spread: -3.5
  total: 37.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w18/SF_vs_ARI.md
  home: SF
  away: ARI
  spread: -14.0
  total: 40.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w18/WAS_vs_DAL.md
  home: WAS
  away: DAL
  spread: 7.5
  total: 40.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w18/DEN_vs_LAC.md
  home: DEN
  away: LAC
  spread: -6.0
  total: 38.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w18/PHI_vs_NYG.md
  home: PHI
  away: NYG
  spread: -16.5
  total: 42.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w18/SEA_vs_LA.md
  home: SEA
  away: LA
  spread: -5.5
  total: 41.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w18/GB_vs_DET.md
  home: GB
  away: DET
  spread: -5.5
  total: 49.0
  prime_time: true
  neutral_site: false
