matchups:
- report: data/reports/comparisons/2022_w11/GB_vs_TEN.md
  home: GB
  away: TEN
  spread: -3.0
  total: 40.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w11/BUF_vs_CLE.md
  home: BUF
  away: CLE
  spread: -7.5
  total: 50.5
  prime_time: false
  neutral_site: true
- report: data/reports/comparisons/2022_w11/NYG_vs_DET.md
  home: NYG
  away: DET
  spread: -3.0
  total: 44.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w11/HOU_vs_WAS.md
  home: HOU
  away: WAS
  spread: 3.0
  total: 41.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w11/NE_vs_NYJ.md
  home: NE
  away: NYJ
  spread: -3.5
  total: 38.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w11/ATL_vs_CHI.md
  home: ATL
  away: CHI
  spread: -3.0
  total: 48.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w11/BAL_vs_CAR.md
  home: BAL
  away: CAR
  spread: -13.0
  total: 42.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w11/IND_vs_PHI.md
  home: IND
  away: PHI
  spread: 6.5
  total: 45.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w11/NO_vs_LA.md
  home: 'NO'
  away: LA
  spread: -2.5
  total: 39.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w11/DEN_vs_LV.md
  home: DEN
  away: LV
  spread: -2.5
  total: 41.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w11/PIT_vs_CIN.md
  home: PIT
  away: CIN
  spread: 3.5
  total: 39.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w11/MIN_vs_DAL.md
  home: MIN
  away: DAL
  spread: 1.5
  total: 48.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w11/LAC_vs_KC.md
  home: LAC
  away: KC
  spread: 5.5
  total: 52.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w11/ARI_vs_SF.md
  home: ARI
  away: SF
  spread: 10.0
  total: 43.5
  prime_time: true
  neutral_site: true
