matchups:
- report: data/reports/comparisons/2022_w5/DEN_vs_IND.md
  home: DEN
  away: IND
  spread: -3.5
  total: 42.0
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w5/GB_vs_NYG.md
  home: GB
  away: NYG
  spread: -8.5
  total: 42.0
  prime_time: false
  neutral_site: true
- report: data/reports/comparisons/2022_w5/TB_vs_ATL.md
  home: TB
  away: ATL
  spread: -10.5
  total: 46.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w5/BUF_vs_PIT.md
  home: BUF
  away: PIT
  spread: -14.0
  total: 44.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w5/MIN_vs_CHI.md
  home: MIN
  away: CHI
  spread: -10.0
  total: 44.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w5/CLE_vs_LAC.md
  home: CLE
  away: LAC
  spread: 1.0
  total: 47.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w5/NE_vs_DET.md
  home: NE
  away: DET
  spread: -3.0
  total: 46.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w5/JAX_vs_HOU.md
  home: JAX
  away: HOU
  spread: -7.0
  total: 44.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w5/NYJ_vs_MIA.md
  home: NYJ
  away: MIA
  spread: 3.0
  total: 46.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w5/NO_vs_SEA.md
  home: 'NO'
  away: SEA
  spread: -5.5
  total: 45.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w5/WAS_vs_TEN.md
  home: WAS
  away: TEN
  spread: 1.0
  total: 43.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w5/CAR_vs_SF.md
  home: CAR
  away: SF
  spread: 6.0
  total: 40.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w5/ARI_vs_PHI.md
  home: ARI
  away: PHI
  spread: 5.5
  total: 48.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w5/LA_vs_DAL.md
  home: LA
  away: DAL
  spread: -5.5
  total: 42.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w5/BAL_vs_CIN.md
  home: BAL
  away: CIN
  spread: -3.0
  total: 47.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w5/KC_vs_LV.md
  home: KC
  away: LV
  spread: -7.5
  total: 51.5
  prime_time: true
  neutral_site: false
