matchups:
- report: data/reports/comparisons/2022_w16/NYJ_vs_JAX.md
  home: NYJ
  away: JAX
  spread: -2.5
  total: 36.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w16/BAL_vs_ATL.md
  home: BAL
  away: ATL
  spread: -6.5
  total: 35.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w16/CHI_vs_BUF.md
  home: CHI
  away: BUF
  spread: 8.0
  total: 40.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w16/CAR_vs_DET.md
  home: CAR
  away: DET
  spread: 2.5
  total: 43.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w16/NE_vs_CIN.md
  home: NE
  away: CIN
  spread: 3.0
  total: 42.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w16/CLE_vs_NO.md
  home: CLE
  away: 'NO'
  spread: -3.0
  total: 32.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w16/TEN_vs_HOU.md
  home: TEN
  away: HOU
  spread: -3.0
  total: 34.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w16/KC_vs_SEA.md
  home: KC
  away: SEA
  spread: -10.5
  total: 50.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w16/MIN_vs_NYG.md
  home: MIN
  away: NYG
  spread: -4.5
  total: 48.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w16/SF_vs_WAS.md
  home: SF
  away: WAS
  spread: -6.5
  total: 37.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w16/DAL_vs_PHI.md
  home: DAL
  away: PHI
  spread: -4.0
  total: 48.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w16/PIT_vs_LV.md
  home: PIT
  away: LV
  spread: -2.5
  total: 38.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w16/MIA_vs_GB.md
  home: MIA
  away: GB
  spread: -3.5
  total: 49.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w16/LA_vs_DEN.md
  home: LA
  away: DEN
  spread: 3.0
  total: 36.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w16/ARI_vs_TB.md
  home: ARI
  away: TB
  spread: 7.5
  total: 41.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w16/IND_vs_LAC.md
  home: IND
  away: LAC
  spread: 3.5
  total: 44.5
  prime_time: true
  neutral_site: false
