matchups:
- report: data/reports/comparisons/2022_w1/LA_vs_BUF.md
  home: LA
  away: BUF
  spread: 1.0
  total: 51.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w1/ATL_vs_NO.md
  home: ATL
  away: 'NO'
  spread: 6.0
  total: 43.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w1/CAR_vs_CLE.md
  home: CAR
  away: CLE
  spread: -2.5
  total: 42.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w1/CHI_vs_SF.md
  home: CHI
  away: SF
  spread: 6.5
  total: 38.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w1/CIN_vs_PIT.md
  home: CIN
  away: PIT
  spread: -7.5
  total: 44.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w1/HOU_vs_IND.md
  home: HOU
  away: IND
  spread: 7.0
  total: 46.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w1/DET_vs_PHI.md
  home: DET
  away: PHI
  spread: 6.0
  total: 49.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w1/WAS_vs_JAX.md
  home: WAS
  away: JAX
  spread: -3.0
  total: 43.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w1/MIA_vs_NE.md
  home: MIA
  away: NE
  spread: -3.0
  total: 47.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w1/NYJ_vs_BAL.md
  home: NYJ
  away: BAL
  spread: 6.5
  total: 44.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w1/ARI_vs_KC.md
  home: ARI
  away: KC
  spread: 6.0
  total: 54.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w1/MIN_vs_GB.md
  home: MIN
  away: GB
  spread: -2.5
  total: 47.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w1/TEN_vs_NYG.md
  home: TEN
  away: NYG
  spread: -5.5
  total: 43.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w1/LAC_vs_LV.md
  home: LAC
  away: LV
  spread: -3.5
  total: 52.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w1/DAL_vs_TB.md
  home: DAL
  away: TB
  spread: 2.5
  total: 49.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w1/SEA_vs_DEN.md
  home: SEA
  away: DEN
  spread: 6.0
  total: 44.0
  prime_time: true
  neutral_site: false
