matchups:
- report: data/reports/comparisons/2022_w2/KC_vs_LAC.md
  home: KC
  away: LAC
  spread: -4.0
  total: 52.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w2/NYG_vs_CAR.md
  home: NYG
  away: CAR
  spread: 1.0
  total: 44.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w2/CLE_vs_NYJ.md
  home: CLE
  away: NYJ
  spread: -6.5
  total: 38.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w2/JAX_vs_IND.md
  home: JAX
  away: IND
  spread: 3.0
  total: 43.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w2/DET_vs_WAS.md
  home: DET
  away: WAS
  spread: 1.0
  total: 48.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w2/BAL_vs_MIA.md
  home: BAL
  away: MIA
  spread: -3.0
  total: 44.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w2/NO_vs_TB.md
  home: 'NO'
  away: TB
  spread: 2.5
  total: 44.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w2/PIT_vs_NE.md
  home: PIT
  away: NE
  spread: 3.0
  total: 40.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w2/LA_vs_ATL.md
  home: LA
  away: ATL
  spread: -10.5
  total: 46.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w2/SF_vs_SEA.md
  home: SF
  away: SEA
  spread: -8.5
  total: 40.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w2/DAL_vs_CIN.md
  home: DAL
  away: CIN
  spread: 7.5
  total: 42.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w2/LV_vs_ARI.md
  home: LV
  away: ARI
  spread: -5.5
  total: 51.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w2/DEN_vs_HOU.md
  home: DEN
  away: HOU
  spread: -10.5
  total: 46.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w2/GB_vs_CHI.md
  home: GB
  away: CHI
  spread: -10.5
  total: 42.0
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w2/BUF_vs_TEN.md
  home: BUF
  away: TEN
  spread: -10.0
  total: 47.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w2/PHI_vs_MIN.md
  home: PHI
  away: MIN
  spread: -2.5
  total: 49.5
  prime_time: true
  neutral_site: false
