matchups:
- report: data/reports/comparisons/2022_w6/CHI_vs_WAS.md
  home: CHI
  away: WAS
  spread: 1.0
  total: 38.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w6/ATL_vs_SF.md
  home: ATL
  away: SF
  spread: 3.5
  total: 46.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w6/NO_vs_CIN.md
  home: 'NO'
  away: CIN
  spread: 3.0
  total: 42.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w6/CLE_vs_NE.md
  home: CLE
  away: NE
  spread: -2.5
  total: 43.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w6/IND_vs_JAX.md
  home: IND
  away: JAX
  spread: -1.0
  total: 41.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w6/GB_vs_NYJ.md
  home: GB
  away: NYJ
  spread: -7.5
  total: 44.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w6/MIA_vs_MIN.md
  home: MIA
  away: MIN
  spread: 3.0
  total: 45.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w6/NYG_vs_BAL.md
  home: NYG
  away: BAL
  spread: 5.5
  total: 46.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w6/PIT_vs_TB.md
  home: PIT
  away: TB
  spread: 10.0
  total: 47.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w6/LA_vs_CAR.md
  home: LA
  away: CAR
  spread: -10.0
  total: 41.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w6/SEA_vs_ARI.md
  home: SEA
  away: ARI
  spread: 2.5
  total: 50.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w6/KC_vs_BUF.md
  home: KC
  away: BUF
  spread: 2.5
  total: 54.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w6/PHI_vs_DAL.md
  home: PHI
  away: DAL
  spread: -6.5
  total: 42.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w6/LAC_vs_DEN.md
  home: LAC
  away: DEN
  spread: -3.5
  total: 45.5
  prime_time: true
  neutral_site: false
