matchups:
- report: data/reports/comparisons/2022_w10/CAR_vs_ATL.md
  home: CAR
  away: ATL
  spread: 2.5
  total: 41.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w10/TB_vs_SEA.md
  home: TB
  away: SEA
  spread: -2.5
  total: 45.0
  prime_time: false
  neutral_site: true
- report: data/reports/comparisons/2022_w10/BUF_vs_MIN.md
  home: BUF
  away: MIN
  spread: -6.5
  total: 47.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w10/MIA_vs_CLE.md
  home: MIA
  away: CLE
  spread: -3.0
  total: 49.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w10/TEN_vs_DEN.md
  home: TEN
  away: DEN
  spread: -2.5
  total: 40.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w10/NYG_vs_HOU.md
  home: NYG
  away: HOU
  spread: -5.5
  total: 41.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w10/CHI_vs_DET.md
  home: CHI
  away: DET
  spread: -3.0
  total: 48.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w10/KC_vs_JAX.md
  home: KC
  away: JAX
  spread: -10.0
  total: 51.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w10/PIT_vs_NO.md
  home: PIT
  away: 'NO'
  spread: -1.0
  total: 39.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w10/LV_vs_IND.md
  home: LV
  away: IND
  spread: -4.5
  total: 41.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w10/GB_vs_DAL.md
  home: GB
  away: DAL
  spread: 3.5
  total: 44.5
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w10/LA_vs_ARI.md
  home: LA
  away: ARI
  spread: -3.5
  total: 38.0
  prime_time: false
  neutral_site: false
- report: data/reports/comparisons/2022_w10/SF_vs_LAC.md
  home: SF
  away: LAC
  spread: -8.5
  total: 45.5
  prime_time: true
  neutral_site: false
- report: data/reports/comparisons/2022_w10/PHI_vs_WAS.md
  home: PHI
  away: WAS
  spread: -11.0
  total: 43.0
  prime_time: true
  neutral_site: false
